# Generated by Django 5.0.7 on 2024-08-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Mobile_no', models.CharField(max_length=20)),
                ('Application_type', models.CharField(choices=[('caste', 'Caste'), ('income', 'Income'), ('non-creamy', 'Non creamy'), ('possession', 'Possession'), ('etapp', 'Etapp'), ('landtax', 'Landtax')], max_length=10)),
                ('Application_status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], max_length=10)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('Date', models.DateField()),
            ],
        ),
    ]
