# Generated by Django 5.0.7 on 2024-08-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appadh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newapplication',
            name='Application_no',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newapplication',
            name='Application_type',
            field=models.CharField(choices=[('caste', 'Caste'), ('income', 'Income'), ('non-creamy', 'Non creamy'), ('possession', 'Possession'), ('etapp', 'Etapp'), ('landtax', 'Landtax')], max_length=20),
        ),
    ]
